//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    get(): Promise<PowerRankingDto[]> {
        let url_ = this.baseUrl + "/api/power_rankings/Get";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: Response): Promise<PowerRankingDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(PowerRankingDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PowerRankingDto[]>(null as any);
    }
}

export class PowerRankingDto implements IPowerRankingDto {
    rank?: number;
    team?: TeamDto;

    constructor(data?: IPowerRankingDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.rank = _data["rank"];
            this.team = _data["team"] ? TeamDto.fromJS(_data["team"]) : <any>undefined;
        }
    }

    static fromJS(data: any): PowerRankingDto {
        data = typeof data === 'object' ? data : {};
        let result = new PowerRankingDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["rank"] = this.rank;
        data["team"] = this.team ? this.team.toJSON() : <any>undefined;
        return data;
    }
}

export interface IPowerRankingDto {
    rank?: number;
    team?: TeamDto;
}

export class TeamDto implements ITeamDto {
    id?: number;
    name?: string | undefined;
    description?: string | undefined;
    wins?: number;
    losses?: number;
    pointsFor?: number;
    pointsAgainst?: number;
    gamesPlayed?: number;
    strengthOfSchedule?: number;
    rating?: number;
    speed?: number;

    constructor(data?: ITeamDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.wins = _data["wins"];
            this.losses = _data["losses"];
            this.pointsFor = _data["pointsFor"];
            this.pointsAgainst = _data["pointsAgainst"];
            this.gamesPlayed = _data["gamesPlayed"];
            this.strengthOfSchedule = _data["strengthOfSchedule"];
            this.rating = _data["rating"];
            this.speed = _data["speed"];
        }
    }

    static fromJS(data: any): TeamDto {
        data = typeof data === 'object' ? data : {};
        let result = new TeamDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        data["wins"] = this.wins;
        data["losses"] = this.losses;
        data["pointsFor"] = this.pointsFor;
        data["pointsAgainst"] = this.pointsAgainst;
        data["gamesPlayed"] = this.gamesPlayed;
        data["strengthOfSchedule"] = this.strengthOfSchedule;
        data["rating"] = this.rating;
        data["speed"] = this.speed;
        return data;
    }
}

export interface ITeamDto {
    id?: number;
    name?: string | undefined;
    description?: string | undefined;
    wins?: number;
    losses?: number;
    pointsFor?: number;
    pointsAgainst?: number;
    gamesPlayed?: number;
    strengthOfSchedule?: number;
    rating?: number;
    speed?: number;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}